(defpackage #:glop-bridge
  (:use #:cl #:cffi)
  (:export #:cf-bundle-get-bundle-with-identifier
           #:cf-bundle-get-function-pointer-for-name
           #:copy-all-display-modes
           #:copy-display-mode
           #:glop-app-next-event
           #:glop-app-run
           #:glop-app-run-iteration
           #:glop-app-send-event
           #:glop-app-shared-application
           #:glop-app-update-windows
           #:main-display-id
           #:mode-height
           #:mode-pixel-encoding
           #:mode-rate
           #:mode-width
           #:ns-application-shared-application
           #:ns-array-count
           #:ns-array-object-at-index
           #:ns-autorelease
           #:ns-autorelease-pool-alloc-init
           #:ns-black-color
           #:ns-blue-color
           #:ns-brown-color
           #:ns-cyan-color
           #:ns-dark-gray-color
           #:ns-gray-color
           #:ns-green-color
           #:ns-light-gray-color
           #:ns-magenta-color
           #:ns-orange-color
           #:ns-purple-color
           #:ns-release
           #:ns-retain
           #:ns-string-alloc-init-with-c-string
           #:ns-string-c-string-using-encoding
           #:ns-string-to-lisp
           #:ns-string-to-lisp-string
           #:ns-white-color
           #:ns-window-alloc-init
           #:ns-window-make-key-and-order-front
           #:ns-window-set-background-color
           #:ns-yellow-color
           #:with-ns-autorelease-pool))